stages:
    - build
    - test

default:
    image: julia:1.7.0

build-job:
    stage: build
    tags:
        - linux
    script:
        - rm -rf packages
        - mkdir packages
        - export JULIA_DEPOT_PATH=./packages
        - julia $CI_BUILDS_DIR/iasonaspg/randomized-block-lanczos/Julia/packages.jl

cache:
    paths:
        - packages/

test-slow-dec:
    stage: test
    tags:
        - linux
    script:
        - export JULIA_DEPOT_PATH=./packages
        - julia $CI_BUILDS_DIR/iasonaspg/randomized-block-lanczos/Julia/Unit\ Testing/slow_dec.jl

test-mod-dec:
    stage: test
    tags:
        - linux
    script:
        - export JULIA_DEPOT_PATH=./packages
        - julia $CI_BUILDS_DIR/iasonaspg/randomized-block-lanczos/Julia/Unit\ Testing/mod_dec.jl

test-step-dec:
    stage: test
    tags:
        - linux
    script:
        - export JULIA_DEPOT_PATH=./packages
        - julia $CI_BUILDS_DIR/iasonaspg/randomized-block-lanczos/Julia/Unit\ Testing/step_dec.jl
