stages:
    - build
    - test

default:
    image: julia:1.6.2

build-job:
    stage: build
    tags:
        - linux
    script:
        - echo "Building"

test-slow-dec:
    stage: test
    tags:
        - linux
    script:
        - julia $CI_BUILDS_DIR/iasonaspg/randomized-block-lanczos/Julia/Unit\ Testing\slow_dec.jl

test-mod-dec:
    stage: test
    tags:
        - linux
    script:
        - julia $CI_BUILDS_DIR/iasonaspg/randomized-block-lanczos/Julia/Unit\ Testing\mod_dec.jl

test-step-dec:
    stage: test
    tags:
        - linux
    script:
        - julia $CI_BUILDS_DIR/iasonaspg/randomized-block-lanczos/Julia/Unit\ Testing\step_dec.jl
