stages:
    - build
    - test

default:
    image: julia:1.6.2

build-job:
    stage: build
    tags:
        - linux
    script:
        - echo "Building"
        - ls $CI_BUILDS_DIR/iasonaspg/randomized-block-lanczos


test-job:
    stage: test
    tags:
        - linux
    script:
        - echo "Testing"
